version: '3'
services:
  xmpp-server:
    image: ejabberd/ecs
    container_name: ejabberd
    volumes:
      - './ejabberd-new.yml:/home/ejabberd/conf/ejabberd.yml'
      - ./database:/home/ejabberd/database
    restart: always
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    # network_mode: 'host'